# Use postgres/postgres user/password credentials
version: '3'

services:
  app:
    image: app:1.0-alpine
    restart: always
    build: .
    ports:
      - "7070:8080"
    env_file:
      - pgdb.env
  goserver:
    image: goserver:1.0-alpine
    restart: always
    build: ./app/src/go
    ports: 
      - "7071:8081"
  pgdb:
    image: postgres:9.5-alpine
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--data-checksums"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
